package app.home.utils;

public class Data {

  public Data() {}

  String privatePolicyExpectedText =
    "¿Quién es el Responsable del tratamiento de sus datos?\n" + //
    "EAE Institución Superior de Formación Universitaria, S.L., con CIF B64273956, será la responsable de los datos personales facilitados a través de la presente página web, así como de los facilitados telefónicamente, a través de cualquiera de nuestros formularios en formato papel, de los obtenidos como consecuencia de la relación que Usted mantenga con nosotros y de los derivados de sus hábitos de navegación y consumo. Dicha compañía se encuentra ubicada en Avda. Diagonal 662-664, 08034 Barcelona, pudiendo ponerse en contacto con la misma a través de la dirección electrónica eae@eae.es.\n" + //
    "Igualmente, podrá ponerse en contacto con nuestro Delegado de Protección de Datos mediante escrito dirigido a dpo@planeta.es o a Grupo Planeta, At.: Delegado de Protección de Datos, Avda. Diagonal 662-664, 08034 Barcelona.\n" + //
    "¿Con qué finalidad tratamos sus datos personales?\n" + //
    "EAE Institución Superior de Formación Universitaria, S.L., tratará sus datos personales con el fin de gestionar la relación que Usted mantiene con nosotros así como para enviarle comunicaciones comerciales por cualquier vía, para mantenerle informado de aquellos de nuestros productos y servicios similares a los solicitados por Usted.\n" + //
    "Asimismo, le informamos que, con el fin de poder ofrecerle productos y servicios de EAE Institución Superior de Formación Universitaria, S.L., o de terceras empresas adecuados a sus intereses, así como para mejorar su experiencia de usuario de nuestra página Web, elaboraremos un “perfil comercial” en base tanto a la información facilitada por Usted como a aquella otra derivada de sus hábitos de consumo y navegación y la obtenida de redes sociales.\n" + //
    "Adicionalmente, sus datos personales y perfil comercial serán cedidos al resto de empresas del Grupo Planeta para que éstas le remitan comunicaciones comerciales sobre sus propios productos y servicios o de terceras empresas pertenecientes o ajenas al Grupo Planeta, elaborando para ello, a su vez, su propio perfil comercial con dichos datos y perfiles, así como con los datos y perfiles de Usted que ya tuviera u obtenga, todo ello, para que dichas comunicaciones sean de su interés por adecuarse a sus gustos, hábitos de consumo y navegación y preferencias comerciales. Este tratamiento implicará, por tanto, el cruce de bases de datos de las distintas empresas del Grupo Planeta y enriquecimiento de las mismas.\n" + //
    "Puede consultar el listado de empresas del Grupo Planeta en el siguiente link www.planeta.es. Dichas empresas desarrollan su actividad en los sectores editorial, formación, cultura, ocio, coleccionismo, textil, seguros privados, gran consumo y joyería.\n" + //
    "En cualquier caso, las terceras empresas ajenas a nuestro grupo de las que, en su caso, le enviaremos comunicaciones comerciales serán aquellas que desarrollen su actividad en los mismos sectores que las empresas del Grupo Planeta y que han sido indicados anteriormente, o en los sectores de Telecomunicaciones, bancario y financiero, viajes, tecnología y actividades jurídicas.\n" + //
    "¿Por cuánto tiempo conservaremos sus datos?\n" + //
    "Los datos personales tratados con la finalidad de gestionar la relación con usted, serán conservados mientras dure dicha relación y, una vez finalizada ésta, por el plazo legal en que pudiera derivarse alguna responsabilidad derivada de dicha relación.\n" + //
    "Por otro lado, los datos y perfil comercial, tratados con la finalidad de hacerle llegar comunicaciones comerciales, basadas en su consentimiento, serán conservados mientras no revoque dicho consentimiento o ejerza su derecho de oposición o supresión, así como, posteriormente, el tiempo durante el cual pudiera derivarse algún tipo de responsabilidad.\n" + //
    "Los datos obtenidos a través de cookies, o dispositivos de almacenamiento y recuperación de datos se conservarán por el plazo indicado en nuestra política de cookies, la cual puede consultar en (incluir link a la política de cookies definitivo).\n" + //
    "¿Cuál es la legitimación para el tratamiento de sus datos?\n" + //
    "La base legal para el tratamiento de sus datos personales es la ejecución y mantenimiento de la relación mantenida con Usted, así como el consentimiento expreso que, en su caso, nos haya facilitado para los tratamientos adicionales consistentes en el envío de comunicaciones comerciales propias y/o de terceros, la elaboración de perfiles comerciales y la cesión de dichos datos y perfiles al resto de empresas del Grupo Planeta con las finalidades indicadas en el apartado “¿Con qué finalidad tratamos sus datos personales?” anterior.\n" + //
    "Le informamos que los datos personales que se solicitan en el momento de registrarse en la presente página web, los solicitados telefónicamente o en cualquiera de nuestros formularios en formato papel, son los estrictamente necesarios para formalizar y gestionar la relación con Usted, de manera que, en caso de no facilitarlos, no podremos mantener dicha relación. En cualquier caso, dicha finalidad principal no está supeditada al consentimiento para el tratamiento de los datos que no sean necesarios para dicha actividad principal.\n" + //
    "Como, hemos indicado anteriormente, la oferta prospectiva de productos y servicios propios y/o de terceros, así como la elaboración de perfiles comerciales y la cesión de dichos perfiles y de sus datos personales a terceras empresas del Grupo Planeta, son tratamientos adicionales que están basados en el consentimiento que se le solicita, sin que en ningún caso la retirada de este consentimiento condicione el mantenimiento de la relación que mantiene con nosotros.\n" + //
    "¿A qué destinatarios se comunicarán sus datos?\n" + //
    "Únicamente en el caso de que nos dé su consentimiento para ello, sus datos personales y, en su caso, su perfil comercial serán comunicados al resto de empresas del Grupo Planeta con las finalidades indicadas en el punto “¿Con qué finalidad tratamos sus datos personales?” de la presente política de privacidad. Puede consultar el listado de empresas del Grupo Planeta en el siguiente link www.planeta.es.\n" + //
    "¿Cuáles son sus derechos cuando nos facilita sus datos?\n" + //
    "Cualquier persona tiene derecho a obtener confirmación sobre si en EAE Institución Superior de Formación Universitaria, S.L., estamos tratando datos personales que les conciernan, o no.\n" + //
    "Asimismo, las personas interesadas tienen derecho a acceder a sus datos personales, así como a solicitar la rectificación de los datos inexactos o, en su caso, solicitar su supresión cuando, entre otros motivos, los datos ya no sean necesarios para los fines que fueron recogidos.\n" + //
    "En determinadas circunstancias, los interesados podrán solicitar la limitación del tratamiento de sus datos, en cuyo caso únicamente los conservaremos para el ejercicio o la defensa de reclamaciones.\n" + //
    "En determinadas circunstancias y por motivos relacionados con su situación particular, los interesados podrán oponerse al tratamiento de sus datos. EAE Institución Superior de Formación Universitaria, S.L., dejará de tratar los datos, salvo por motivos legítimos imperiosos, o el ejercicio o la defensa de posibles reclamaciones.\n" + //
    "Asimismo, los interesados tienen derecho a recibir, en un formato estructurado, de uso común y lectura mecánica, los datos personales que le incumban que nos hayan facilitado, y a transmitirlos a otro responsable.\n" + //
    "Los interesados, podrán ejercer dichos derechos y la revocación en cualquier momento de los consentimientos en su caso prestados, mediante carta dirigida a EAE Institución Superior de Formación Universitaria, S.L., Apartado de Correos 221 de Barcelona o remitiendo un email a lopd@eae.es. En este sentido, le informamos que tiene a su disposición modelos de ejercicio de los citados derechos en la página web de la Agencia Española de Protección de Datos (https://www.aepd.es/es/derechos-y-deberes/conoce-tus-derechos).\n" + //
    "Cuando el interesado lo considere oportuno podrá presentar una reclamación ante la Agencia Española de Protección de Datos, especialmente cuando aquél considere que no hemos satisfecho debidamente el ejercicio de sus derechos. Dicha reclamación podrá presentarla ante la citada autoridad mediante las diferentes opciones que la sede electrónica de la Agencia Española de Protección de Datos ofrece.";

  public String getPrivatePolicyExpectedText() {
    return privatePolicyExpectedText;
  }

  public void setPrivatePolicyExpectedText(String privatePolicyExpectedText) {
    this.privatePolicyExpectedText = privatePolicyExpectedText;
  }
}
